kind: pipeline
name: default

steps:
- name: install packages
  image: node:10.15.3-jessie
  volumes:
  - name: yarn-cache
    path: /usr/local/share/.cache/yarn/v4
  commands:
  - yarn
  when:
    event:
    - pull_request

- name: build
  image: node:10.15.3-jessie
  commands:
  - export STAGING_BRANCH=pr$DRONE_PULL_REQUEST
  - yarn build
  when:
    event:
    - pull_request
    status:
    - success
    - failure

volumes:
  name: yarn-cache
  path: /var/lib/docker/volumes/yarn-cache/_data
