kind: pipeline
name: default

clone:
  disable: true

steps:
- name: clone
  image: drone/git
  commands:
  - clone
  when:
    event:
    - pull_request

- name: restore node_modules cache
  image: codesandbox-cache:1
  settings:
    restore: true
  volumes:
  - name: node_modules-cache
    path: /cache
  when:
    event:
    - pull_request

- name: install packages
  image: node:10.15.3-jessie
  volumes:
  - name: yarn-cache
    path: /usr/local/share/.cache/yarn/v4
  commands:
  - yarn
  when:
    event:
    - pull_request

- name: build
  image: node:10.15.3-jessie
  commands:
  - export STAGING_BRANCH=pr$DRONE_PULL_REQUEST
  - yarn build
  when:
    event:
    - pull_request
    status:
    - success
    - failure

- name: rebuild node_modules cache
  image: codesandbox-cache:1
  settings:
    rebuild: true
  volumes:
  - name: node_modules-cache
    path: /cache
  when:
    event:
    - pull_request

volumes:
- name: yarn-cache
  host:
    path: /var/lib/docker/volumes/yarn-cache/_data
- name: node_modules-cache
  host:
    path: /var/lib/docker/volumes/node_modules-cache/_data
